### ISSUE TITLE
Current subsite is not actually applied

### ISSUE THREAD

**Issue by phptek** [Firesphere/silverstripe-subsite-solr#3]
firesphere/silverstripe-solr-search + firesphere/silverstripe-subsite-solr `dev-master`, Silverstripe 4.4.3 on PHP7.2

Using a single subsite, search results are not filtered correctly when performing a search from a given subsite.

Note, bug was filed in the context of a DEV env, using the ?SubsiteID=1 URL hack.

**Comment by phptek** [comment]
Note: Ref's conversation in Slack here: https://silverstripe-users.slack.com/archives/C9KB3U0P8/p1579562395002000

Note also the following repro steps:

Steps to reproduce:

* Setup YML config as per Slack convo
* Setup manual exclusions (if required) as per PHP snippet in Slack convo
* Run the configure task
* Run the index task
* Query Solr directly - observe no relevant results are returned for fl=SiteTree_SubsiteID

http://localhost:8983/solr/MyIndex/select?fl=SiteTree_SubsiteID&q=*%3A*

```
{
  "responseHeader":{
    "status":0,
    "QTime":0,
    "params":{
      "q":"*:*",
      "fl":"SiteTree_SubsiteID"}},
  "response":{"numFound":5944,"start":0,"docs":[
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {}]
  }}
```

**Comment by Firesphere** [comment]
Do you have a non-Subsite object in your index? It seems like the results are correct, but because there is no Subsite associated, the result is not what is expected....

Just a hunch :) Not sure if it's related, but it seems to matter for me

**Comment by Firesphere** [comment]
I _think_ I got it fixed:
![image](https://user-images.githubusercontent.com/680570/75100179-64093c80-562f-11ea-97e3-20c49b594233.png)
Please test?
